server {
    listen 80;
    server_name intranet.mail.smarttech.sn;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name intranet.mail.smarttech.sn;

    # Certificats (à adapter selon vos chemins)
    ssl_certificate /etc/ssl/certs/votre_certificat.crt;
    ssl_certificate_key /etc/ssl/private/votre_cle.key;

    # RACINE VERS VOTRE APP CRUD
    root /var/www/html/techsupport;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
}

}
